image: mofesola/bitbucket-ecs-deploy
options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo 'No test scripts defined yet. Proceeding to deploy'

  branches:
        master:
          - step:
              script:
              - envsubst < ~/.aws/credentials.tmpl > ~/.aws/credentials
              - envsubst < scripts/newrelic.ini > scripts/newrelic2.ini && mv scripts/newrelic2.ini scripts/newrelic.ini
              - conf/build.sh
              - ecs deploy ppv-prod ppv-prod-website -e ppv-website DB_NAME ${DB_NAME} -e ppv-website DB_USER ${DB_USER} -e ppv-website DB_PASSWORD ${DB_PASSWORD} -e ppv-website DB_HOST ${DB_HOST}
