image: mofesola/bitbucket-ecs-deploy
options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo 'No test scripts defined yet. Proceeding to deploy'

  branches:
        develop:
          - step:
              script:
              - source deploy/dev/export-dev.sh
              - deploy/dev/build-dev.sh
              - deploy/dev/deploy-dev.sh

        master:
          - step:
              script:
              - source deploy/prod/export-prod.sh
              - deploy/prod/build-prod.sh
              - deploy/prod/deploy-prod.sh